contact_links:
  - name: Discord
    about: Seu problema é urgente? Contate a gente no Discord!
    url: https://discord.gg/ZtN9UH7XZu
  - name: Telegram
    about: Não possui Discord? Venha no Telegram!
    url: https://t.me/PROJETOIRIS
