exports.translate = require('./translate')
exports.msgFilter = require('./msgFilter')
exports.meme = require('./meme')
exports.ngtts = require('./tts')
exports.killo = require('./kill')
exports.rank = require('./level')
exports.diario = require('./daily')